version: "3.9"
   
services:
  ethsigner:
    image: consensys/ethsigner:develop
    command: --config-file=/var/config/config.toml multikey-signer
    volumes:
      - ./config:/var/config
    ports:
      - "8545:8545"