version: '3.9'

networks:
  internal_network:
    name: 'web3signer_hashicorp_tls_network'

services:
  vault-ssl-certificate:
    image: alpine:latest
    container_name: 'ws-vault-ssl-certificate'
    command: sh -c /scripts/gen-cert.sh
    volumes:
      - ./certs:/certs
      - ./scripts:/scripts
  
  vault:
    image: hashicorp/vault:latest
    container_name: 'ws-vault-tls'
    command: server -config /config
    ports:
      - "8200:8200"
    volumes:
      - "./certs:/tls"
      - "./data:/data"
      - "./config:/config"
    environment:
      - 'VAULT_SKIP_VERIFY=true'
      - 'VAULT_ENABLE_FILE_PERMISSIONS_CHECK=false'
    cap_add:
      - IPC_LOCK
    depends_on:
      vault-ssl-certificate:
        condition: service_completed_successfully
    networks:
      - internal_network
  
  init-vault:
    image: usmans/init-vault
    build:
      context: ./initvault
    container_name: "ws-vault-init"
    volumes:
      - ./creds:/creds
    depends_on:
      vault:
        condition: service_started
    command: https://vault:8200
    networks:
      - internal_network