# Chain
chain-id=2017

logging="TRACE"

# Path
data-path="/var/config/data"

# Ethereum client (Besu)
downstream-http-host="localhost"
downstream-http-port=8546

# CORS
http-cors-origins="*"

# Metrics
metrics-enabled=true
metrics-port=9546

# Signing options

# multi-key
multikey-signer.directory="/var/config/keys"

# TLS options
tls-keystore-file="/var/config/tls/keystore.p12"
tls-keystore-password-file="/var/config/tls/password.txt"
tls-known-clients-file="/var/config/tls/knownClients.txt"
#tls-allow-any-client=true
