version: '3.8'

services:
  web3signer_migrations:
    image: "docker.io/consensys/web3signer:${WEB3SIGNER_TAG:-develop}"
    volumes:
      - ./migrations:/flyway/sql
    entrypoint: ["sh", "-c", "rm /flyway/sql/*.sql; cp /opt/web3signer/migrations/postgresql/*.sql /flyway/sql/; echo 'sql files copied!'"] 

  db:
    image: "docker.io/bitnami/postgresql:${PG_TAG:-14}"
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=web3signer
      - POSTGRESQL_PORT_NUMBER=5431  
    ports:
      - '5431:5431'
    networks:
      - testnet
    volumes: 
      - dbdata:/bitnami/postgresql
    depends_on:
      web3signer_migrations:
        condition: service_completed_successfully

  pgbouncer:
    image: "docker.io/bitnami/pgbouncer:${PG_BOUNCER_TAG:-1}"
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=web3signer
      - POSTGRESQL_PORT=5431
      - PGBOUNCER_DATABASE=web3signer
      - PGBOUNCER_PORT=5432  
      - PGBOUNCER_AUTH_TYPE=md5
      - PGBOUNCER_AUTH_FILE=/pgbouncer_auth/pgbouncer_auth.txt  
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits  
    volumes:
      - ./pgbouncer_auth:/pgbouncer_auth:ro
    ports:
      - '5432:5432'       
    depends_on:
      - db
    networks:
      - testnet

  flyway:
    image: "docker.io/flyway/flyway:${FLYWAY_TAG:-latest}"
    command: -url=jdbc:postgresql://pgbouncer:5432/web3signer -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql:ro
    depends_on:
      pgbouncer:
        condition: service_started
      db:
        condition: service_started      
      web3signer_migrations:
        condition: service_completed_successfully       
    networks:
      - testnet


  web3signer:
    image: "docker.io/consensys/web3signer:${WEB3SIGNER_TAG:-develop}"
    command: --config-file=/var/config/config.yaml eth2
    volumes:
      - ./config:/var/config
    ports:
      - "9000:9000"
    networks:
      - testnet
    depends_on:
      flyway:      
        condition: service_completed_successfully

volumes:
  dbdata:

networks:
  testnet:
    name: pgbouncer_w3s_network
